In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.svm import SVR

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

import mlflow

/home/kibria/miniconda3/envs/Uber/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# set the dagshub tracking server

mlflow.set_tracking_uri("https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow")

In [4]:
import dagshub
dagshub.init(repo_owner='gulamkibria775', repo_name='Uber-Demand-Prediction', mlflow=True)

Accessing as gulamkibria775

Initialized MLflow to track repo "gulamkibria775/Uber-Demand-Prediction"

Repository gulamkibria775/Uber-Demand-Prediction initialized!

In [5]:
# load the training and test data

train_data_path = "../data/processed/train.csv"
test_data_path = "../data/processed/test.csv"

train_df = pd.read_csv(train_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

test_df = pd.read_csv(test_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

train_df

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,12.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,14.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,15.0,0

In [6]:
# missing value in training data

train_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [7]:
# missing values in the test data

test_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [8]:
# make X_train and y_train

X_train = train_df.drop(columns=["total_pickups"])

y_train = train_df["total_pickups"]

In [9]:
X_train.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185.0,4

In [10]:
# make X_test and y_test

X_test = test_df.drop(columns=["total_pickups"])

y_test = test_df["total_pickups"]

In [11]:
X_test.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-03-01 00:00:00,36.0,44.0,31.0,29.0,0,38.0,1
2016-03-01 00:15:00,41.0,36.0,44.0,31.0,0,39.0,1
2016-03-01 00:30:00,35.0,41.0,36.0,44.0,0,37.0,1
2016-03-01 00:45:00,47.0,35.0,41.0,36.0,0,41.0,1
2016-03-01 01:00:00,34.0,47.0,35.0,41.0,0,38.0,1

In [12]:
from sklearn import set_config

set_config(transform_output="pandas")

In [13]:
# encode the data

encoder = ColumnTransformer([
    ("ohe", OneHotEncoder(drop="first",sparse_output=False), ["region","day_of_week"])
], remainder="passthrough", n_jobs=-1,force_int_remainder_cols=False)

In [14]:
encoder

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['region', 'day_of_week'])])

In [15]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

/home/kibria/miniconda3/envs/Uber/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

In [17]:
import optuna
import tqdm

In [18]:
# set the experiment

mlflow.set_experiment("Model Selection")

2026/04/20 23:21:22 INFO mlflow.tracking.fluent: Experiment with name 'Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/6da9ee55a62d4893989a556d49b2d0ac', creation_time=1776705683068, experiment_id='1', last_update_time=1776705683068, lifecycle_stage='active', name='Model Selection', tags={}, trace_location=None, workspace='default'>

In [19]:
def objective(trial):
    # start the child run
    with mlflow.start_run(nested=True) as child:
        
        # model name search space
        list_of_models = ["LR", "RF", "GBR", "XGBR"]
        model_name = trial.suggest_categorical("model_name", list_of_models)
    
        if model_name == "LR":
            model = LinearRegression()
    
        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,100,step=10)
            max_depth_rf = trial.suggest_int("max_depth_rf",3,10)
            model = RandomForestRegressor(n_estimators=n_estimators_rf, 
                                          max_depth=max_depth_rf, 
                                          random_state=42, n_jobs=-1)
    
        elif model_name == "GBR":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,100,step=10)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",1e-4,1e-1, log=True)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb, 
                                              learning_rate=learning_rate_gb,
                                             random_state=42)
    
        elif model_name == "XGBR":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,100,step=10)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",1e-4,1e-1, log=True)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",3,10)
            model = XGBRegressor(n_estimators=n_estimators_xgb,
                                learning_rate=learning_rate_xgb,
                                max_depth=max_depth_xgb)
    
        # log the model name
        mlflow.log_param("model_name",model_name)
        
        # log the model parameters
        mlflow.log_params(model.get_params())
        
        # fit on the data
        model.fit(X_train_encoded,y_train)
    
        # get the predictions
        y_pred = model.predict(X_test_encoded)
    
        # calculate the loss
        loss = mean_absolute_percentage_error(y_test, y_pred)
    
        # log the metric
        mlflow.log_metric("MAPE",loss)
        return loss

In [20]:
# optimize the objective function

with mlflow.start_run(run_name="best_model", nested=True) as parent:

    # create a study object
    study = optuna.create_study(study_name="model_selection", direction="minimize")
    # optimize the objective function
    study.optimize(func=objective, n_trials=50, n_jobs=-1)
    
    # log the best parameters
    mlflow.log_params(study.best_params)
    # log the best error value
    mlflow.log_metric("Best_MAPE", study.best_value)

[I 2026-04-20 23:22:32,651] A new study created in memory with name: model_selection

🏃 View run loud-lynx-546 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/16ca2dcd1f6942d8aabb1ec3daa87752
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:23:06,069] Trial 0 finished with value: 5.9415602684021 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.010395578277685112, 'max_depth_xgb': 7}. Best is trial 0 with value: 5.9415602684021.

🏃 View run calm-sow-809 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/23528159d846432285c4016c82fc155d
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run luxuriant-gull-350 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/f548aab39b9045088dd4907742af6c71
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run colorful-lamb-60 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/fac6d95ef03343568292595d2b2505a7
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run agreeable-worm-930 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/7dbae13959bf47dca7706b136cb61da1
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run dapper-hare-719 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/f1bd9e9b622b499f944a1aa76af13228
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run able-moth-558 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/3960091ecdf24817ad7717d17a0bf8ec
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:23:26,995] Trial 6 finished with value: 0.29003821492025283 and parameters: {'model_name': 'RF', 'n_estimators_rf': 80, 'max_depth_rf': 10}. Best is trial 6 with value: 0.29003821492025283.

🏃 View run receptive-stag-950 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/2cbc70f09a014adcb738ab4270913340
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:23:28,996] Trial 1 finished with value: 0.2899647733881066 and parameters: {'model_name': 'RF', 'n_estimators_rf': 100, 'max_depth_rf': 10}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:23:32,019] Trial 7 finished with value: 0.28996610771606146 and parameters: {'model_name': 'RF', 'n_estimators_rf': 70, 'max_depth_rf': 10}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run luminous-zebra-472 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/005b6ef8ddee4fa683beab3d4f369336
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run calm-bear-950 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/b6d6822d98294c5c8719537303cf4cdf
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:23:34,975] Trial 3 finished with value: 5.425667762756348 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 70, 'learning_rate_xgb': 0.002832934382166716, 'max_depth_xgb': 5}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:23:36,068] Trial 12 finished with value: 2.024245969997705 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 40, 'learning_rate_gb': 0.032545094215982215}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run dapper-lark-413 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/5c28e9d7ab6f4f209b4754fc46020d40
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run flawless-duck-572 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/d96df70e268842859e8ad96caaa0485b
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:23:43,000] Trial 14 finished with value: 0.3252742186859446 and parameters: {'model_name': 'RF', 'n_estimators_rf': 100, 'max_depth_rf': 5}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:23:44,148] Trial 10 finished with value: 5.009842593943997 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 30, 'learning_rate_gb': 0.009718514858503396}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:23:45,039] Trial 2 finished with value: 6.4802327156066895 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 40, 'learning_rate_xgb': 0.0003830086231616538, 'max_depth_xgb': 5}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:23:47,979] Trial 8 finished with value: 0.3069871006888052 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:23:51,217] Trial 9 finished with value: 0.4987964245997022 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 60, 'learning_rate_gb': 0.055857045719943176}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run calm-colt-183 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/a165db7892ec4e62b66ae774f4025f0f
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run beautiful-vole-23 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/c41e951f1d3443418df430604eaececa
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run welcoming-roo-348 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/5923962d8ce144098c8c0ad95a1f54f1
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run persistent-foal-265 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/2486a3d9fb81402ebdf61d7f6bc8874d
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:24:26,991] Trial 16 finished with value: 1.322548270225525 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.017191982344421524, 'max_depth_xgb': 6}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:24:29,032] Trial 15 finished with value: 0.3069871006888052 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run amazing-seal-706 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/b5945b541fef428488b13dd984e75d2d
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:24:31,015] Trial 4 finished with value: 6.07432746887207 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 20, 'learning_rate_xgb': 0.004079450050584584, 'max_depth_xgb': 8}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run honorable-sloth-377 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/263914c8caa246e192d02b8f52878f81
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run delightful-panda-272 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/ff8acb839bf34b2e96ab8446c1142b26
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:24:36,071] Trial 18 finished with value: 0.3069871006888052 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run dapper-horse-850 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/854afe40a87740f38fb7c0b850623b5b
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run thoughtful-wasp-733 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/90a0bf1769da4a3f81bed47bf75830ce
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:24:40,167] Trial 21 finished with value: 0.2965486999690216 and parameters: {'model_name': 'RF', 'n_estimators_rf': 90, 'max_depth_rf': 8}. Best is trial 1 with value: 0.2899647733881066.

🏃 View run bald-crab-833 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/2397885ead314ac89e4b1ebb90013bb8
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run righteous-goose-204 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/a1ffa1808ca34d1284c48cfa5c1449b9
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:24:44,154] Trial 19 finished with value: 1.295421430945636 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 90, 'learning_rate_gb': 0.020654077663491567}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:24:45,035] Trial 13 finished with value: 0.5718715612607599 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 30, 'learning_rate_gb': 0.09995197628904728}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:24:47,023] Trial 17 finished with value: 0.360850989818573 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 40, 'learning_rate_xgb': 0.09604572898670093, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.2899647733881066.
[I 2026-04-20 23:24:48,387] Trial 22 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run popular-ray-120 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/1a0627d12e3d4f219c842c957b7706fb
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:24:52,148] Trial 26 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:24:53,013] Trial 25 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:25:04,980] Trial 23 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run funny-slug-697 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/4dc1827fefde40d780897afb67e79fe2
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:25:16,566] Trial 20 finished with value: 0.3069871006888052 and parameters: {'model_name': 'LR'}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run whimsical-hawk-198 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/aa1ef0f6a8a24b15b28cdd541b70e5ec
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:25:31,465] Trial 28 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run abundant-perch-894 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/ec94a415a43148b195387b5ab175f080
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run stately-loon-721 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/8d310cfdc9ff4cd381e0a524354844fa
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run adorable-hen-945 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/6eb604aae12d47d3a6884830a986e29d
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:25:42,445] Trial 30 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run enchanting-skink-640 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/026b3e05735b48758f2a3135d2672473
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:25:45,652] Trial 11 finished with value: 0.5717571315597667 and parameters: {'model_name': 'RF', 'n_estimators_rf': 100, 'max_depth_rf': 3}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:25:52,507] Trial 24 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:25:53,516] Trial 31 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run invincible-moth-871 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/7261ff2ed32a42f8a8d110b83f83e645
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run charming-shad-176 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/a3925bc671bd45feb7a99378a8ea80fa
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run likeable-shad-351 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/df4377041ecf49df8d8f19419a60e121
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run youthful-wren-969 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/6afe3152a47046779dfb5625356366bb
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:26:03,463] Trial 35 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:26:04,599] Trial 27 finished with value: 0.2963463016961937 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run honorable-steed-473 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/e4a7df70855d41e1bf03966dbcd71287
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:26:07,671] Trial 38 finished with value: 0.2963463016961937 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:26:10,640] Trial 29 finished with value: 0.28987187209242254 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:26:16,470] Trial 32 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run marvelous-seal-368 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/4f3c4a04597c4b239a279728b6c28382
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run overjoyed-mouse-719 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/ba432116e9054b3dbaa745ed0f83986a
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:26:31,454] Trial 39 finished with value: 0.2963463016961937 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:26:32,657] Trial 40 finished with value: 0.29624688326177795 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run puzzled-crow-519 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/b072eef569894feba8df189a06d37fe0
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run suave-stoat-68 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/98c1618b5c614075bf0c308b3655f71c
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:26:46,586] Trial 42 finished with value: 0.29632878555291886 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:26:47,610] Trial 41 finished with value: 0.2963287855529188 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run amusing-gnu-757 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/166e1c6077404d6e9264777f5077fc78
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run peaceful-moose-244 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/ebede3ea9bf742b8b88d2b27c14bf18d
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run dapper-sow-494 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/264e89bfd2b94f6c85da8cc61c0b80eb
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run rebellious-bird-286 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/f5b82ae79e714c9c999e2fbc6b469eea
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:26:57,463] Trial 37 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run ambitious-quail-909 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/0eb623fbdbfa457cbfc3b30730d8f562
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run capricious-sow-326 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/2fe116ea6a4b4014987199df571626be
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1
🏃 View run delightful-snail-848 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/46de322b8ce64a0e8dd3bc8c778bf56e
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:27:01,620] Trial 45 finished with value: 0.2927734728597436 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:27:04,689] Trial 44 finished with value: 0.2927734728597436 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run tasteful-chimp-729 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/5529585a995542f2864f5dce2ebf3430
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:27:07,757] Trial 46 finished with value: 0.2927734728597436 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:27:08,421] Trial 47 finished with value: 0.2927734728597436 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:27:09,497] Trial 48 finished with value: 0.2927734728597436 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:27:10,624] Trial 43 finished with value: 0.2963287855529188 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:27:11,648] Trial 36 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run masked-yak-337 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/30e3f84c76484b8daaddb33722bd4f0c
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:27:13,488] Trial 49 finished with value: 0.2927734728597436 and parameters: {'model_name': 'RF', 'n_estimators_rf': 50, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.
[I 2026-04-20 23:27:16,675] Trial 33 finished with value: 0.2961956568506344 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 8}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run whimsical-cod-417 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/5ac60ecc472e41499ab9d6b6bed52029
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:27:19,516] Trial 5 finished with value: 5.87486468268694 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 40, 'learning_rate_gb': 0.0030120266640552974}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run able-hen-139 at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/9853c48f6a544aa281d6dbd8d13e270d
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

[I 2026-04-20 23:27:22,593] Trial 34 finished with value: 0.2927120884443459 and parameters: {'model_name': 'RF', 'n_estimators_rf': 40, 'max_depth_rf': 9}. Best is trial 22 with value: 0.28987187209242254.

🏃 View run best_model at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1/runs/f01b767bbdd84c149c105792a7465c9a
🧪 View experiment at: https://dagshub.com/gulamkibria775/Uber-Demand-Prediction.mlflow/#/experiments/1

In [21]:
# best value

study.best_value

0.28987187209242254

In [22]:
# best parameters

study.best_params

{'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 10}

In [23]:
# model value counts

study.trials_dataframe()['params_model_name'].value_counts()

params_model_name
RF      34
XGBR     6
GBR      6
LR       4
Name: count, dtype: int64

In [24]:
from optuna.visualization import (
    plot_optimization_history, 
    plot_parallel_coordinate, 
    plot_param_importances
)

In [27]:
plot_optimization_history(study)

ImportError: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.

In [28]:
plot_parallel_coordinate(study, params=["model_name"])

ImportError: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.

In [29]:
# train the linear regression model

lr = LinearRegression()

lr.fit(X_train_encoded, y_train)

# get predictions
y_pred_train = lr.predict(X_train_encoded) 
y_pred_test = lr.predict(X_test_encoded)

# loss

mape_train = mean_absolute_percentage_error(y_train, y_pred_train)
mape_test = mean_absolute_percentage_error(y_test, y_pred_test)

print("The training error is ", mape_train)
print("The test error is ", mape_test)

The training error is  0.31749731735894027
The test error is  0.3069871006888052

In [30]:
lr.coef_

array([ 6.59266116, -2.05638952,  1.61048142,  3.5589809 ,  9.08819126,
        2.48639847,  7.8520678 , 10.1342072 , -1.11046656,  8.27602693,
        5.45456779, 10.55872532, -1.47820493,  7.18907985,  6.87749488,
       -1.37837448, -1.70783813, 13.33847201,  5.6738974 ,  3.55876455,
       11.32924195,  5.90374261,  2.88449163, -2.03676138,  2.83674402,
        2.42578855,  6.85780565, -1.94162399, -1.62963472,  0.64633354,
        0.93102079,  1.43743235,  1.61026612,  0.91215046, -0.468891  ,
        1.40961414,  0.49144781,  0.28244361,  0.18601736, -1.42136691])

In [31]:
def tune_ridge(trial):
    # hyperparameter space
    alpha = trial.suggest_float("alpha",30,100)
    
    # make the model object
    ridge = Ridge(alpha=alpha, random_state=42)
    
    # train the model
    ridge.fit(X_train_encoded, y_train)
    
    # get predictions
    y_pred = ridge.predict(X_test_encoded)
    
    # calculate loss
    loss = mean_absolute_percentage_error(y_test, y_pred)

    return loss

In [32]:
# create study

study = optuna.create_study(study_name="tune_model", direction="minimize")

[I 2026-04-20 23:30:28,061] A new study created in memory with name: tune_model

In [33]:
# optimize

study.optimize(func=tune_ridge, n_trials=100, n_jobs=-1, show_progress_bar=True)

Best trial: 4. Best value: 0.306878:  11%|█         | 11/100 [00:00<00:04, 19.82it/s]

[I 2026-04-20 23:30:41,542] Trial 2 finished with value: 0.3070367673853913 and parameters: {'alpha': 96.37192152287254}. Best is trial 2 with value: 0.3070367673853913.
[I 2026-04-20 23:30:41,551] Trial 7 finished with value: 0.30688004049479756 and parameters: {'alpha': 43.798427937707906}. Best is trial 7 with value: 0.30688004049479756.
[I 2026-04-20 23:30:41,556] Trial 5 finished with value: 0.30693534256053917 and parameters: {'alpha': 71.33323690591902}. Best is trial 7 with value: 0.30688004049479756.
[I 2026-04-20 23:30:41,560] Trial 4 finished with value: 0.30687806474513757 and parameters: {'alpha': 37.53345357074372}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,568] Trial 1 finished with value: 0.30695124910766186 and parameters: {'alpha': 76.0298659145573}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,573] Trial 14 finished with value: 0.3069142237544348 and parameters: {'alpha': 64.06867644146271}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,573] Trial 8 finished with value: 0.30699227194123896 and parameters: {'alpha': 86.49851638685669}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,577] Trial 6 finished with value: 0.3069895761853342 and parameters: {'alpha': 85.86170840859732}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,577] Trial 0 finished with value: 0.3068786983436494 and parameters: {'alpha': 41.14754241333894}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,577] Trial 11 finished with value: 0.30690267924968234 and parameters: {'alpha': 59.28493254992269}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,578] Trial 13 finished with value: 0.3069997776430954 and parameters: {'alpha': 88.24651273881338}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,578] Trial 9 finished with value: 0.3069850450819917 and parameters: {'alpha': 84.7787252973807}. Best is trial 4 with value: 0.30687806474513757.

Best trial: 4. Best value: 0.306878:  19%|█▉        | 19/100 [00:00<00:02, 30.55it/s]

[I 2026-04-20 23:30:41,579] Trial 3 finished with value: 0.3069497701841342 and parameters: {'alpha': 75.61312982497543}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,580] Trial 15 finished with value: 0.30691732912990716 and parameters: {'alpha': 65.22605120504977}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,586] Trial 10 finished with value: 0.30688164731965323 and parameters: {'alpha': 30.667656180844173}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,588] Trial 12 finished with value: 0.30692498165864557 and parameters: {'alpha': 67.94108230007137}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,682] Trial 16 finished with value: 0.30688162289467713 and parameters: {'alpha': 45.89995607817602}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,738] Trial 19 finished with value: 0.3068834549164627 and parameters: {'alpha': 47.82451473555373}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,739] Trial 17 finished with value: 0.30688421057134063 and parameters: {'alpha': 48.517226275946854}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,742] Trial 20 finished with value: 0.3068835401645694 and parameters: {'alpha': 47.90476418337846}. Best is trial 4 with value: 0.30687806474513757.

[I 2026-04-20 23:30:41,745] Trial 18 finished with value: 0.3068837928468662 and parameters: {'alpha': 48.139751612599774}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,807] Trial 22 finished with value: 0.3068796621486066 and parameters: {'alpha': 33.080515471829116}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,841] Trial 21 finished with value: 0.3068845256753839 and parameters: {'alpha': 48.79295089198679}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,919] Trial 25 finished with value: 0.306879317387977 and parameters: {'alpha': 33.629406610655835}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,928] Trial 24 finished with value: 0.30688047169776905 and parameters: {'alpha': 31.9762221430303}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,929] Trial 23 finished with value: 0.3068810394869188 and parameters: {'alpha': 31.316429174976342}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,930] Trial 26 finished with value: 0.3068815321532568 and parameters: {'alpha': 30.78669148621889}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:41,973] Trial 27 finished with value: 0.30688061943736056 and parameters: {'alpha': 31.796647309797265}. Best is trial 4 with value: 0.30687806474513757.

Best trial: 30. Best value: 0.306878:  37%|███▋      | 37/100 [00:01<00:01, 32.68it/s]

[I 2026-04-20 23:30:41,984] Trial 28 finished with value: 0.3068805731821856 and parameters: {'alpha': 31.851890571968916}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:42,069] Trial 31 finished with value: 0.30687820679721595 and parameters: {'alpha': 39.4206830006445}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:42,108] Trial 29 finished with value: 0.30688068451162187 and parameters: {'alpha': 31.720281606432163}. Best is trial 4 with value: 0.30687806474513757.
[I 2026-04-20 23:30:42,112] Trial 30 finished with value: 0.30687804873641195 and parameters: {'alpha': 37.995407150873625}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,113] Trial 33 finished with value: 0.3068783251679618 and parameters: {'alpha': 39.958322507730145}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,133] Trial 32 finished with value: 0.3068782262291854 and parameters: {'alpha': 39.521242022694715}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,146] Trial 34 finished with value: 0.30687822076320986 and parameters: {'alpha': 39.493442781443854}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,158] Trial 35 finished with value: 0.30687838100320086 and parameters: {'alpha': 40.16850579190377}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,170] Trial 36 finished with value: 0.3068784078453052 and parameters: {'alpha': 40.26402081898493}. Best is trial 30 with value: 0.30687804873641195.

[I 2026-04-20 23:30:42,261] Trial 38 finished with value: 0.30687810784090497 and parameters: {'alpha': 38.80051827942096}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,268] Trial 39 finished with value: 0.30689099879352705 and parameters: {'alpha': 53.329779461270135}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,268] Trial 37 finished with value: 0.30689407429269594 and parameters: {'alpha': 55.10013343069305}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,296] Trial 41 finished with value: 0.3068970925239165 and parameters: {'alpha': 56.655357946194286}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,321] Trial 40 finished with value: 0.3068933272722547 and parameters: {'alpha': 54.683635333415126}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,364] Trial 42 finished with value: 0.30689379295963565 and parameters: {'alpha': 54.94470465473172}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,450] Trial 43 finished with value: 0.3068800221013554 and parameters: {'alpha': 43.77019223275173}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,530] Trial 49 finished with value: 0.3068780519581416 and parameters: {'alpha': 38.131229676272916}. Best is trial 30 with value: 0.30687804873641195.

[I 2026-04-20 23:30:42,538] Trial 44 finished with value: 0.3068780708976921 and parameters: {'alpha': 37.44803850313822}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,542] Trial 46 finished with value: 0.3068783412361941 and parameters: {'alpha': 35.91776780788147}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,543] Trial 45 finished with value: 0.3068799708428074 and parameters: {'alpha': 43.690934675237116}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,543] Trial 48 finished with value: 0.3068780695325859 and parameters: {'alpha': 37.46617343499994}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,543] Trial 47 finished with value: 0.3068782716532734 and parameters: {'alpha': 36.18031543917077}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,582] Trial 50 finished with value: 0.30687819655441795 and parameters: {'alpha': 36.52171350191435}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,623] Trial 51 finished with value: 0.3068782291030891 and parameters: {'alpha': 36.36380466736687}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,677] Trial 52 finished with value: 0.3068781894415011 and parameters: {'alpha': 36.561288669621746}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,709] Trial 55 finished with value: 0.3068782609766681 and parameters: {'alpha': 36.22425588611145}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,716] Trial 53 finished with value: 0.30687830178186054 and parameters: {'alpha': 36.06051669605697}. Best is trial 30 with value: 0.30687804873641195.

[I 2026-04-20 23:30:42,723] Trial 54 finished with value: 0.30688804874983516 and parameters: {'alpha': 51.43853446689134}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,744] Trial 56 finished with value: 0.30687812085671223 and parameters: {'alpha': 36.999871320665434}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,758] Trial 57 finished with value: 0.30705302115121696 and parameters: {'alpha': 99.6898341412184}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,789] Trial 58 finished with value: 0.3070545528888818 and parameters: {'alpha': 99.99649028762387}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,823] Trial 59 finished with value: 0.3068876268426997 and parameters: {'alpha': 51.14888986247466}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,869] Trial 61 finished with value: 0.30687956613306333 and parameters: {'alpha': 43.012179165874876}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:42,886] Trial 60 finished with value: 0.3068799573138048 and parameters: {'alpha': 43.66987305241397}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,002] Trial 64 finished with value: 0.306879282636038 and parameters: {'alpha': 42.477758619980094}. Best is trial 30 with value: 0.30687804873641195.

Best trial: 30. Best value: 0.306878:  69%|██████▉   | 69/100 [00:02<00:00, 36.81it/s]

[I 2026-04-20 23:30:43,038] Trial 62 finished with value: 0.30687949134767417 and parameters: {'alpha': 42.875732256670766}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,038] Trial 63 finished with value: 0.3068794546297787 and parameters: {'alpha': 42.807616413703016}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,048] Trial 66 finished with value: 0.3068818396063597 and parameters: {'alpha': 46.151785468664485}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,053] Trial 65 finished with value: 0.306961149905969 and parameters: {'alpha': 78.74170012236037}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,054] Trial 67 finished with value: 0.30688172997810964 and parameters: {'alpha': 46.025362533630314}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,104] Trial 70 finished with value: 0.3068789584501072 and parameters: {'alpha': 41.79327992416838}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,125] Trial 69 finished with value: 0.3069630106407286 and parameters: {'alpha': 79.23636194289807}. Best is trial 30 with value: 0.30687804873641195.

Best trial: 30. Best value: 0.306878:  78%|███████▊  | 78/100 [00:02<00:00, 44.81it/s]

[I 2026-04-20 23:30:43,132] Trial 68 finished with value: 0.30696193919489306 and parameters: {'alpha': 78.9521411918003}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,163] Trial 71 finished with value: 0.3069440012401982 and parameters: {'alpha': 73.95226617194449}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,194] Trial 72 finished with value: 0.30687805243237254 and parameters: {'alpha': 37.7588860462585}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,261] Trial 73 finished with value: 0.3068791554683081 and parameters: {'alpha': 33.92273594262796}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,261] Trial 74 finished with value: 0.3068780613038146 and parameters: {'alpha': 38.34253283457754}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,272] Trial 76 finished with value: 0.30687897236721995 and parameters: {'alpha': 34.2775348516895}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,285] Trial 75 finished with value: 0.30687958489910827 and parameters: {'alpha': 33.19787510108895}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,315] Trial 77 finished with value: 0.3068792388748343 and parameters: {'alpha': 33.76906730613727}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,401] Trial 78 finished with value: 0.30687928292717087 and parameters: {'alpha': 33.689654405903184}. Best is trial 30 with value: 0.30687804873641195.

Best trial: 30. Best value: 0.306878:  89%|████████▉ | 89/100 [00:02<00:00, 45.49it/s]

[I 2026-04-20 23:30:43,430] Trial 79 finished with value: 0.3068790008401904 and parameters: {'alpha': 34.220629951854264}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,434] Trial 81 finished with value: 0.3068781552990544 and parameters: {'alpha': 39.12607977717148}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,435] Trial 80 finished with value: 0.30687807583554816 and parameters: {'alpha': 38.52833306060758}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,488] Trial 84 finished with value: 0.30688217837359 and parameters: {'alpha': 30.139421167639483}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,493] Trial 82 finished with value: 0.30688223519294217 and parameters: {'alpha': 30.084682553349815}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,495] Trial 83 finished with value: 0.3068781656543662 and parameters: {'alpha': 39.189235414859965}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,626] Trial 85 finished with value: 0.3068781691597353 and parameters: {'alpha': 39.21011438383619}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,646] Trial 86 finished with value: 0.30687806089331676 and parameters: {'alpha': 38.33491641872529}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,646] Trial 87 finished with value: 0.3068780564410897 and parameters: {'alpha': 37.668692104895044}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,662] Trial 89 finished with value: 0.3068780517818315 and parameters: {'alpha': 38.126035216889264}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,663] Trial 90 finished with value: 0.3068780509058283 and parameters: {'alpha': 37.80551913357662}. Best is trial 30 with value: 0.30687804873641195.

Best trial: 30. Best value: 0.306878: 100%|██████████| 100/100 [00:02<00:00, 37.49it/s]

[I 2026-04-20 23:30:43,665] Trial 88 finished with value: 0.306878050637173 and parameters: {'alpha': 38.09025775151626}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,765] Trial 91 finished with value: 0.3068780488946229 and parameters: {'alpha': 37.95530648108646}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,779] Trial 92 finished with value: 0.3068780547760143 and parameters: {'alpha': 37.701109366234235}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,793] Trial 93 finished with value: 0.3068780577533894 and parameters: {'alpha': 37.64526750793011}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,832] Trial 95 finished with value: 0.3068788797082771 and parameters: {'alpha': 41.60852944448773}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,834] Trial 94 finished with value: 0.3068786027082026 and parameters: {'alpha': 40.8819001998138}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,858] Trial 96 finished with value: 0.30687889070488544 and parameters: {'alpha': 41.63476957146176}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,914] Trial 97 finished with value: 0.3068787411534705 and parameters: {'alpha': 41.260920875804246}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,917] Trial 98 finished with value: 0.3068786781055933 and parameters: {'alpha': 41.092839708602504}. Best is trial 30 with value: 0.30687804873641195.
[I 2026-04-20 23:30:43,918] Trial 99 finished with value: 0.3068788795410038 and parameters: {'alpha': 41.60812915601753}. Best is trial 30 with value: 0.30687804873641195.

In [34]:
# best parameters

study.best_params

{'alpha': 37.995407150873625}

In [35]:
# best value

study.best_value

0.30687804873641195